import { test, expect } from '@playwright/test';

test.describe('GovernancePanel', () => {
  test('should display proposals and allow creation', async ({ page }) => {
    await page.goto('http://localhost:4173');
    
    // Navigate to the Governance tab
    const accordionBtn = page.locator('.tab-nav-accordion > button');
    if (await accordionBtn.isVisible()) {
      await accordionBtn.click();
    }
    await page.locator('button.tab-btn').filter({ hasText: 'Governance' }).first().click();
    
    // Verify sections exist
    await expect(page.getByText('Active Proposals', { exact: false })).toBeVisible();
    await expect(page.getByText('Create Proposal', { exact: false })).toBeVisible();
    await expect(page.getByText('Proposal History', { exact: false })).toBeVisible();

    // Verify Create Proposal form
    await expect(page.locator('#proposal-title')).toBeVisible();
    await expect(page.locator('#proposal-category')).toBeVisible();
    await expect(page.locator('#proposal-desc')).toBeVisible();
    
    // Create a new proposal
    await page.fill('#proposal-title', 'E2E Test Proposal');
    await page.fill('#proposal-desc', 'This is a test proposal generated by Playwright.');
    await page.click('button:has-text("Submit Proposal")');
    
    // Verify proposal appears
    await expect(page.getByText('E2E Test Proposal')).toBeVisible();
  });
});
